export const SUPPORTED_CHAINS = {
  ethereum: {
    id: "ethereum",
    label: "Ethereum",
    symbol: "ETH",
    chainId: 1,
    ankrSlug: "eth",
    tokenApiSlug: "eth",
    rpcFamily: "evm",
    explorer: "https://etherscan.io",
    confirmations: 12,
    color: "#8f83ff",
  },
  polygon: {
    id: "polygon",
    label: "Polygon",
    symbol: "POL",
    chainId: 137,
    ankrSlug: "polygon",
    tokenApiSlug: "polygon",
    rpcFamily: "evm",
    explorer: "https://polygonscan.com",
    confirmations: 80,
    color: "#8f5cff",
  },
  bsc: {
    id: "bsc",
    label: "BNB Smart Chain",
    symbol: "BNB",
    chainId: 56,
    ankrSlug: "bsc",
    tokenApiSlug: "bsc",
    rpcFamily: "evm",
    explorer: "https://bscscan.com",
    confirmations: 20,
    color: "#f3ba2f",
  },
  arbitrum: {
    id: "arbitrum",
    label: "Arbitrum",
    symbol: "ETH",
    chainId: 42161,
    ankrSlug: "arbitrum",
    tokenApiSlug: "arbitrum",
    rpcFamily: "evm",
    explorer: "https://arbiscan.io",
    confirmations: 20,
    color: "#4d8dff",
  },
  optimism: {
    id: "optimism",
    label: "Optimism",
    symbol: "ETH",
    chainId: 10,
    ankrSlug: "optimism",
    tokenApiSlug: "optimism",
    rpcFamily: "evm",
    explorer: "https://optimistic.etherscan.io",
    confirmations: 20,
    color: "#ff4b5c",
  },
  base: {
    id: "base",
    label: "Base",
    symbol: "ETH",
    chainId: 8453,
    ankrSlug: "base",
    tokenApiSlug: "base",
    rpcFamily: "evm",
    explorer: "https://basescan.org",
    confirmations: 20,
    color: "#4f8dff",
  },
  avalanche: {
    id: "avalanche",
    label: "Avalanche",
    symbol: "AVAX",
    chainId: 43114,
    ankrSlug: "avalanche",
    tokenApiSlug: "avalanche",
    rpcFamily: "evm",
    explorer: "https://snowtrace.io",
    confirmations: 20,
    color: "#e84142",
  },
  fantom: {
    id: "fantom",
    label: "Fantom",
    symbol: "FTM",
    chainId: 250,
    ankrSlug: "fantom",
    tokenApiSlug: "fantom",
    rpcFamily: "evm",
    explorer: "https://ftmscan.com",
    confirmations: 20,
    color: "#1969ff",
  },
  gnosis: {
    id: "gnosis",
    label: "Gnosis",
    symbol: "xDAI",
    chainId: 100,
    ankrSlug: "gnosis",
    tokenApiSlug: "gnosis",
    rpcFamily: "evm",
    explorer: "https://gnosisscan.io",
    confirmations: 20,
    color: "#48a987",
  },
  linea: {
    id: "linea",
    label: "Linea",
    symbol: "ETH",
    chainId: 59144,
    ankrSlug: "linea",
    tokenApiSlug: "linea",
    rpcFamily: "evm",
    explorer: "https://lineascan.build",
    confirmations: 20,
    color: "#72f0b0",
  },
  scroll: {
    id: "scroll",
    label: "Scroll",
    symbol: "ETH",
    chainId: 534352,
    ankrSlug: "scroll",
    tokenApiSlug: "scroll",
    rpcFamily: "evm",
    explorer: "https://scrollscan.com",
    confirmations: 20,
    color: "#f4d4aa",
  },
  flare: {
    id: "flare",
    label: "Flare",
    symbol: "FLR",
    chainId: 14,
    ankrSlug: "flare",
    tokenApiSlug: "flare",
    rpcFamily: "evm",
    explorer: "https://flare-explorer.flare.network",
    confirmations: 20,
    color: "#e62058",
  },
  story: {
    id: "story",
    label: "Story",
    symbol: "IP",
    chainId: 1514,
    ankrSlug: "story_mainnet",
    tokenApiSlug: "story_mainnet",
    rpcFamily: "evm",
    explorer: "https://www.storyscan.xyz",
    confirmations: 20,
    color: "#72e2ff",
  },
  syscoin: {
    id: "syscoin",
    label: "Syscoin",
    symbol: "SYS",
    chainId: 57,
    ankrSlug: "syscoin",
    tokenApiSlug: "syscoin",
    rpcFamily: "evm",
    explorer: "https://explorer.syscoin.org",
    confirmations: 20,
    color: "#00a4ff",
  },
  taiko: {
    id: "taiko",
    label: "Taiko",
    symbol: "ETH",
    chainId: 167000,
    ankrSlug: "taiko",
    tokenApiSlug: "taiko",
    rpcFamily: "evm",
    explorer: "https://taikoscan.io",
    confirmations: 20,
    color: "#e81899",
  },
  telos: {
    id: "telos",
    label: "Telos",
    symbol: "TLOS",
    chainId: 40,
    ankrSlug: "telos",
    tokenApiSlug: "telos",
    rpcFamily: "evm",
    explorer: "https://teloscan.io",
    confirmations: 20,
    color: "#7048e8",
  },
  xai: {
    id: "xai",
    label: "Xai",
    symbol: "XAI",
    chainId: 660279,
    ankrSlug: "xai",
    tokenApiSlug: "xai",
    rpcFamily: "evm",
    explorer: "https://explorer.xai-chain.net",
    confirmations: 20,
    color: "#f24a62",
  },
  xlayer: {
    id: "xlayer",
    label: "X Layer",
    symbol: "OKB",
    chainId: 196,
    ankrSlug: "xlayer",
    tokenApiSlug: "xlayer",
    rpcFamily: "evm",
    explorer: "https://www.oklink.com/xlayer",
    confirmations: 20,
    color: "#121212",
  },
  stellar: {
    id: "stellar",
    label: "Stellar",
    symbol: "XLM",
    ankrSlug: "stellar",
    tokenApiSlug: "stellar",
    rpcFamily: "stellar",
    explorer: "https://stellar.expert",
    confirmations: 1,
    color: "#dce3ef",
  },
};

export const EVM_CHAIN_IDS = Object.values(SUPPORTED_CHAINS)
  .filter((chain) => chain.rpcFamily === "evm")
  .map((chain) => chain.id);

export const TOKEN_API_CHAIN_IDS = Object.values(SUPPORTED_CHAINS)
  .filter((chain) => chain.tokenApiSlug)
  .map((chain) => chain.id);

export function tokenApiSlug(chainId) {
  const chain = SUPPORTED_CHAINS[chainId];
  if (!chain?.tokenApiSlug) throw new Error(`Unsupported Ankr Token API chain: ${chainId}`);
  return chain.tokenApiSlug;
}

export const TOKEN_REGISTRY = [
  {
    chain: "ethereum",
    symbol: "USDC",
    name: "USD Coin",
    decimals: 6,
    address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
  },
  {
    chain: "polygon",
    symbol: "USDC",
    name: "USD Coin",
    decimals: 6,
    address: "0x3c499c542cef5e3811e1192ce70d8cc03d5c3359",
  },
  {
    chain: "bsc",
    symbol: "USDT",
    name: "Tether USD",
    decimals: 18,
    address: "0x55d398326f99059fF775485246999027B3197955",
  },
  {
    chain: "ethereum",
    symbol: "USDT",
    name: "Tether USD",
    decimals: 6,
    address: "0xdAC17F958D2ee523a2206206994597C13D831ec7",
  },
  {
    chain: "polygon",
    symbol: "USDT",
    name: "Tether USD",
    decimals: 6,
    address: "0xc2132D05D31c914a87C6611C10748AEb04B58e8F",
  },
  {
    chain: "base",
    symbol: "USDC",
    name: "USD Coin",
    decimals: 6,
    address: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913",
  },
  {
    chain: "arbitrum",
    symbol: "USDC",
    name: "USD Coin",
    decimals: 6,
    address: "0xaf88d065e77c8cC2239327C5EDb3A432268e5831",
  },
  {
    chain: "optimism",
    symbol: "USDC",
    name: "USD Coin",
    decimals: 6,
    address: "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85",
  },
  {
    chain: "avalanche",
    symbol: "USDC",
    name: "USD Coin",
    decimals: 6,
    address: "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E",
  },
  {
    chain: "ethereum",
    symbol: "DAI",
    name: "Dai Stablecoin",
    decimals: 18,
    address: "0x6B175474E89094C44Da98b954EedeAC495271d0F",
  },
  {
    chain: "ethereum",
    symbol: "WBTC",
    name: "Wrapped Bitcoin",
    decimals: 8,
    address: "0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599",
  },
  {
    chain: "ethereum",
    symbol: "LINK",
    name: "Chainlink",
    decimals: 18,
    address: "0x514910771AF9Ca656af840dff83E8264EcF986CA",
  },
  {
    chain: "ethereum",
    symbol: "UNI",
    name: "Uniswap",
    decimals: 18,
    address: "0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984",
  },
  {
    chain: "ethereum",
    symbol: "AAVE",
    name: "Aave",
    decimals: 18,
    address: "0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9",
  },
];

export function buildAnkrUrl(chainId, token = "") {
  const chain = SUPPORTED_CHAINS[chainId];
  if (!chain) {
    throw new Error(`Unsupported chain: ${chainId}`);
  }
  const suffix = token ? `/${token}` : "";
  return `https://rpc.ankr.com/${chain.ankrSlug}${suffix}`;
}

export function buildAnkrMultichainUrl(token = "") {
  const suffix = token ? `/${token}` : "";
  return `https://rpc.ankr.com/multichain${suffix}`;
}
